export const ActionTypes={
    GET_NUMBER_CART:"GET_NUMBER_CART",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    ADD_TO_FAVORITES : "ADD_TO_FAVORITES",
    REMOVE_FROM_FAVORITES : "REMOVE_FROM_FAVORITES",
    INCREMENT_ITEM_QUANTITY:'INCREMENT_ITEM_QUANTITY',
    DECREMENT_ITEM_QUANTITY:'DECREMENT_ITEM_QUANTITY'
}